//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Resources/Controls/Builder.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Builder: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Builder()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Builder"",
    ""maps"": [
        {
            ""name"": ""Robot"",
            ""id"": ""3aee0a0d-1fe6-415b-9cb5-cbfa74666c5c"",
            ""actions"": [
                {
                    ""name"": ""Drive"",
                    ""type"": ""Value"",
                    ""id"": ""a66d17aa-71e0-44a4-b727-aee5943cf845"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""1b26705a-cc40-4860-92df-62558459f698"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Intake"",
                    ""type"": ""Button"",
                    ""id"": ""fd057243-ed52-4308-a82b-5bc711f195fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""3bc13c3f-90b7-4f1b-91fa-4517d014db98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hub"",
                    ""type"": ""Button"",
                    ""id"": ""c327244c-8952-4ce3-a181-1e2dff786e3f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PassLeft"",
                    ""type"": ""Button"",
                    ""id"": ""235dafda-9ffc-4c49-bb6a-3d0ceaa3c932"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PassRight"",
                    ""type"": ""Button"",
                    ""id"": ""354fd2c0-2e44-4c04-96e5-3d1f90a01327"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RobotSpecial"",
                    ""type"": ""Button"",
                    ""id"": ""a74897f4-ab1c-49f9-9f36-651da93d1558"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HumanPlayerDump"",
                    ""type"": ""Button"",
                    ""id"": ""e281116f-4229-4711-ba0a-b89a6b13a914"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlipCamera"",
                    ""type"": ""Button"",
                    ""id"": ""ae49d48a-9aae-49b5-b650-678654b95c5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""24c373a2-98fd-486c-b236-baf8b3b02782"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""e5de202a-02be-45f2-89a8-02f1203a489a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AutoAlign"",
                    ""type"": ""Button"",
                    ""id"": ""5b8ced75-5909-4107-9ec0-7196686cab91"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""eb3f03b1-8fcb-4b5a-bb50-a17473d7b738"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Button"",
                    ""id"": ""f5049467-ff25-41d4-85be-fa846fa9b2f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L3"",
                    ""type"": ""Button"",
                    ""id"": ""84b79a91-d9dc-479c-9ed7-c4899e26a6bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L4"",
                    ""type"": ""Button"",
                    ""id"": ""900f4701-239c-4237-a740-263deaa038ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Barge"",
                    ""type"": ""Button"",
                    ""id"": ""9543f6b2-b23f-42d3-bc1b-82f02a9a32cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AlgaeHigh"",
                    ""type"": ""Button"",
                    ""id"": ""50c8bcf5-8d1f-4c90-93d5-0a38a0a30497"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AlgaeLow"",
                    ""type"": ""Button"",
                    ""id"": ""37633517-f7fd-48c6-9346-afe79d61e597"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AlgaeHold"",
                    ""type"": ""Button"",
                    ""id"": ""fda230f2-1588-4a9e-ad42-dc2899ba9e8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Climb"",
                    ""type"": ""Button"",
                    ""id"": ""e196fe68-acf6-4056-800c-bb234add4955"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""04cd54fc-b4f1-49b4-bc76-56f18656b376"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Drive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""wasd"",
                    ""id"": ""6f1a5853-7263-4b8c-92e8-1b3020ca81f0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drive"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""8875b620-a812-4118-bc73-25cdee304966"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Drive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""e6ef2424-3bca-47cc-8ee5-3b024ada19f5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Drive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""e8634606-f6b1-48af-b105-581f801bd4c1"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Drive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""21755fe3-8964-4777-8226-86d2614fb445"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Drive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""381a6c20-b608-4ef0-a559-4e51ea852957"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""jl"",
                    ""id"": ""50dc8126-253f-48c2-bbf0-1b6892bff0c1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dcb4a2a3-dde4-48ef-8a1d-5d6bc935a7ea"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c411f60c-1ff1-4ffa-bbb6-345ea4745762"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""913e9070-1d7b-4592-a8a0-d2d9cc69ff0c"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b1f1c1b-37a3-4302-aa82-9cceece05c37"",
                    ""path"": ""<Gamepad>/{Menu}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77c7f8c2-dbdd-43c9-95e1-fbbfea1c0201"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e81998c-05c0-4c38-bc5a-315f362774a6"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a6228bd-5377-404a-ae27-e0e673c11f3f"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Intake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d98c127e-4b94-4e95-8b68-73abcb7cc4f1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Intake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcbb02cc-2961-482f-ae8a-b8c0ed52b0cb"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""805baba0-4fcc-4a5b-8a20-dd9c8844c0db"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bba4afb7-ab00-452c-b4bc-e6dd516b89cf"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""HumanPlayerDump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f278dde6-7209-4933-affa-f39a99a6a9e8"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""HumanPlayerDump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cb27d06-c93f-40e9-83f1-edb9b35f6ca4"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""FlipCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bf73979-5110-4e26-b504-efbc1fb653d8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""FlipCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07c206d1-d93e-4d95-8159-9618f1f89161"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""PassRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1caa473b-09d2-40d8-be23-9fc0d692d6d2"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PassRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c210a66-bd2f-4ed1-b8a8-e356438f36f3"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PassLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a85dedfc-a6f8-4f60-8ea1-b66f139050a9"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""PassLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22287d16-2b8a-4961-97d0-d4073749433f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RobotSpecial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe875a8a-2d55-4edc-adaf-59c5585a8502"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RobotSpecial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2127d29c-ea73-480c-a32c-1abba71f1f69"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Hub"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6202a691-5641-4504-8b3d-7326739f14b2"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Hub"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a157bebb-efc4-4ca8-99f4-f56e03097f26"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""638cd2e3-93d1-4dab-9f15-3a50098325a1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1da0758-b7bd-459c-8205-17ea56f247ac"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a1359e8-a002-47ec-8258-2ccee4b98d13"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e8cc305-4c9b-4b52-a08f-0741e8899488"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""L3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ac0d423-48f1-4b3c-8d76-8e2d0f2b7954"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""L3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a97a39f-8426-4661-9806-03b0ec4c2a09"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""L4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78b1edcc-516b-4532-929d-64b3eda3c4d9"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""L4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0e3c335-43ad-4daf-ae38-1ede4b8ecd56"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Barge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83b1562c-5d23-427f-a79f-34f2286cd495"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Barge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3485b3f-14a4-4f26-8d8b-d8457f8c4ee9"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""AlgaeHigh"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""960a4e35-386f-4c78-811e-e721f967a593"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AlgaeHigh"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16f5686d-7728-4698-b034-3fc4ff005469"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""AlgaeLow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f65e29d7-9458-41d1-adf1-40680972c13c"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AlgaeLow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81f658db-4c02-4f54-8ea7-dc115291c5aa"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""AlgaeHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a778e819-b195-41b1-9a6b-ba2bc534f388"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AlgaeHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0568437-4dac-4f53-9449-0f1ff0684083"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Climb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36a3021d-0b34-4a4c-9825-60c5ad3fd83c"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Climb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""547dc778-95f4-4410-acb8-eec83644dab7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""AutoAlign"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78f0ee45-81da-4f9b-bc4a-3531673d3517"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AutoAlign"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Robot
        m_Robot = asset.FindActionMap("Robot", throwIfNotFound: true);
        m_Robot_Drive = m_Robot.FindAction("Drive", throwIfNotFound: true);
        m_Robot_Rotate = m_Robot.FindAction("Rotate", throwIfNotFound: true);
        m_Robot_Intake = m_Robot.FindAction("Intake", throwIfNotFound: true);
        m_Robot_Shoot = m_Robot.FindAction("Shoot", throwIfNotFound: true);
        m_Robot_Hub = m_Robot.FindAction("Hub", throwIfNotFound: true);
        m_Robot_PassLeft = m_Robot.FindAction("PassLeft", throwIfNotFound: true);
        m_Robot_PassRight = m_Robot.FindAction("PassRight", throwIfNotFound: true);
        m_Robot_RobotSpecial = m_Robot.FindAction("RobotSpecial", throwIfNotFound: true);
        m_Robot_HumanPlayerDump = m_Robot.FindAction("HumanPlayerDump", throwIfNotFound: true);
        m_Robot_FlipCamera = m_Robot.FindAction("FlipCamera", throwIfNotFound: true);
        m_Robot_Restart = m_Robot.FindAction("Restart", throwIfNotFound: true);
        m_Robot_Menu = m_Robot.FindAction("Menu", throwIfNotFound: true);
        m_Robot_AutoAlign = m_Robot.FindAction("AutoAlign", throwIfNotFound: true);
        m_Robot_L1 = m_Robot.FindAction("L1", throwIfNotFound: true);
        m_Robot_L2 = m_Robot.FindAction("L2", throwIfNotFound: true);
        m_Robot_L3 = m_Robot.FindAction("L3", throwIfNotFound: true);
        m_Robot_L4 = m_Robot.FindAction("L4", throwIfNotFound: true);
        m_Robot_Barge = m_Robot.FindAction("Barge", throwIfNotFound: true);
        m_Robot_AlgaeHigh = m_Robot.FindAction("AlgaeHigh", throwIfNotFound: true);
        m_Robot_AlgaeLow = m_Robot.FindAction("AlgaeLow", throwIfNotFound: true);
        m_Robot_AlgaeHold = m_Robot.FindAction("AlgaeHold", throwIfNotFound: true);
        m_Robot_Climb = m_Robot.FindAction("Climb", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Robot
    private readonly InputActionMap m_Robot;
    private List<IRobotActions> m_RobotActionsCallbackInterfaces = new List<IRobotActions>();
    private readonly InputAction m_Robot_Drive;
    private readonly InputAction m_Robot_Rotate;
    private readonly InputAction m_Robot_Intake;
    private readonly InputAction m_Robot_Shoot;
    private readonly InputAction m_Robot_Hub;
    private readonly InputAction m_Robot_PassLeft;
    private readonly InputAction m_Robot_PassRight;
    private readonly InputAction m_Robot_RobotSpecial;
    private readonly InputAction m_Robot_HumanPlayerDump;
    private readonly InputAction m_Robot_FlipCamera;
    private readonly InputAction m_Robot_Restart;
    private readonly InputAction m_Robot_Menu;
    private readonly InputAction m_Robot_AutoAlign;
    private readonly InputAction m_Robot_L1;
    private readonly InputAction m_Robot_L2;
    private readonly InputAction m_Robot_L3;
    private readonly InputAction m_Robot_L4;
    private readonly InputAction m_Robot_Barge;
    private readonly InputAction m_Robot_AlgaeHigh;
    private readonly InputAction m_Robot_AlgaeLow;
    private readonly InputAction m_Robot_AlgaeHold;
    private readonly InputAction m_Robot_Climb;
    public struct RobotActions
    {
        private @Builder m_Wrapper;
        public RobotActions(@Builder wrapper) { m_Wrapper = wrapper; }
        public InputAction @Drive => m_Wrapper.m_Robot_Drive;
        public InputAction @Rotate => m_Wrapper.m_Robot_Rotate;
        public InputAction @Intake => m_Wrapper.m_Robot_Intake;
        public InputAction @Shoot => m_Wrapper.m_Robot_Shoot;
        public InputAction @Hub => m_Wrapper.m_Robot_Hub;
        public InputAction @PassLeft => m_Wrapper.m_Robot_PassLeft;
        public InputAction @PassRight => m_Wrapper.m_Robot_PassRight;
        public InputAction @RobotSpecial => m_Wrapper.m_Robot_RobotSpecial;
        public InputAction @HumanPlayerDump => m_Wrapper.m_Robot_HumanPlayerDump;
        public InputAction @FlipCamera => m_Wrapper.m_Robot_FlipCamera;
        public InputAction @Restart => m_Wrapper.m_Robot_Restart;
        public InputAction @Menu => m_Wrapper.m_Robot_Menu;
        public InputAction @AutoAlign => m_Wrapper.m_Robot_AutoAlign;
        public InputAction @L1 => m_Wrapper.m_Robot_L1;
        public InputAction @L2 => m_Wrapper.m_Robot_L2;
        public InputAction @L3 => m_Wrapper.m_Robot_L3;
        public InputAction @L4 => m_Wrapper.m_Robot_L4;
        public InputAction @Barge => m_Wrapper.m_Robot_Barge;
        public InputAction @AlgaeHigh => m_Wrapper.m_Robot_AlgaeHigh;
        public InputAction @AlgaeLow => m_Wrapper.m_Robot_AlgaeLow;
        public InputAction @AlgaeHold => m_Wrapper.m_Robot_AlgaeHold;
        public InputAction @Climb => m_Wrapper.m_Robot_Climb;
        public InputActionMap Get() { return m_Wrapper.m_Robot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RobotActions set) { return set.Get(); }
        public void AddCallbacks(IRobotActions instance)
        {
            if (instance == null || m_Wrapper.m_RobotActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RobotActionsCallbackInterfaces.Add(instance);
            @Drive.started += instance.OnDrive;
            @Drive.performed += instance.OnDrive;
            @Drive.canceled += instance.OnDrive;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @Intake.started += instance.OnIntake;
            @Intake.performed += instance.OnIntake;
            @Intake.canceled += instance.OnIntake;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @Hub.started += instance.OnHub;
            @Hub.performed += instance.OnHub;
            @Hub.canceled += instance.OnHub;
            @PassLeft.started += instance.OnPassLeft;
            @PassLeft.performed += instance.OnPassLeft;
            @PassLeft.canceled += instance.OnPassLeft;
            @PassRight.started += instance.OnPassRight;
            @PassRight.performed += instance.OnPassRight;
            @PassRight.canceled += instance.OnPassRight;
            @RobotSpecial.started += instance.OnRobotSpecial;
            @RobotSpecial.performed += instance.OnRobotSpecial;
            @RobotSpecial.canceled += instance.OnRobotSpecial;
            @HumanPlayerDump.started += instance.OnHumanPlayerDump;
            @HumanPlayerDump.performed += instance.OnHumanPlayerDump;
            @HumanPlayerDump.canceled += instance.OnHumanPlayerDump;
            @FlipCamera.started += instance.OnFlipCamera;
            @FlipCamera.performed += instance.OnFlipCamera;
            @FlipCamera.canceled += instance.OnFlipCamera;
            @Restart.started += instance.OnRestart;
            @Restart.performed += instance.OnRestart;
            @Restart.canceled += instance.OnRestart;
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
            @AutoAlign.started += instance.OnAutoAlign;
            @AutoAlign.performed += instance.OnAutoAlign;
            @AutoAlign.canceled += instance.OnAutoAlign;
            @L1.started += instance.OnL1;
            @L1.performed += instance.OnL1;
            @L1.canceled += instance.OnL1;
            @L2.started += instance.OnL2;
            @L2.performed += instance.OnL2;
            @L2.canceled += instance.OnL2;
            @L3.started += instance.OnL3;
            @L3.performed += instance.OnL3;
            @L3.canceled += instance.OnL3;
            @L4.started += instance.OnL4;
            @L4.performed += instance.OnL4;
            @L4.canceled += instance.OnL4;
            @Barge.started += instance.OnBarge;
            @Barge.performed += instance.OnBarge;
            @Barge.canceled += instance.OnBarge;
            @AlgaeHigh.started += instance.OnAlgaeHigh;
            @AlgaeHigh.performed += instance.OnAlgaeHigh;
            @AlgaeHigh.canceled += instance.OnAlgaeHigh;
            @AlgaeLow.started += instance.OnAlgaeLow;
            @AlgaeLow.performed += instance.OnAlgaeLow;
            @AlgaeLow.canceled += instance.OnAlgaeLow;
            @AlgaeHold.started += instance.OnAlgaeHold;
            @AlgaeHold.performed += instance.OnAlgaeHold;
            @AlgaeHold.canceled += instance.OnAlgaeHold;
            @Climb.started += instance.OnClimb;
            @Climb.performed += instance.OnClimb;
            @Climb.canceled += instance.OnClimb;
        }

        private void UnregisterCallbacks(IRobotActions instance)
        {
            @Drive.started -= instance.OnDrive;
            @Drive.performed -= instance.OnDrive;
            @Drive.canceled -= instance.OnDrive;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @Intake.started -= instance.OnIntake;
            @Intake.performed -= instance.OnIntake;
            @Intake.canceled -= instance.OnIntake;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @Hub.started -= instance.OnHub;
            @Hub.performed -= instance.OnHub;
            @Hub.canceled -= instance.OnHub;
            @PassLeft.started -= instance.OnPassLeft;
            @PassLeft.performed -= instance.OnPassLeft;
            @PassLeft.canceled -= instance.OnPassLeft;
            @PassRight.started -= instance.OnPassRight;
            @PassRight.performed -= instance.OnPassRight;
            @PassRight.canceled -= instance.OnPassRight;
            @RobotSpecial.started -= instance.OnRobotSpecial;
            @RobotSpecial.performed -= instance.OnRobotSpecial;
            @RobotSpecial.canceled -= instance.OnRobotSpecial;
            @HumanPlayerDump.started -= instance.OnHumanPlayerDump;
            @HumanPlayerDump.performed -= instance.OnHumanPlayerDump;
            @HumanPlayerDump.canceled -= instance.OnHumanPlayerDump;
            @FlipCamera.started -= instance.OnFlipCamera;
            @FlipCamera.performed -= instance.OnFlipCamera;
            @FlipCamera.canceled -= instance.OnFlipCamera;
            @Restart.started -= instance.OnRestart;
            @Restart.performed -= instance.OnRestart;
            @Restart.canceled -= instance.OnRestart;
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
            @AutoAlign.started -= instance.OnAutoAlign;
            @AutoAlign.performed -= instance.OnAutoAlign;
            @AutoAlign.canceled -= instance.OnAutoAlign;
            @L1.started -= instance.OnL1;
            @L1.performed -= instance.OnL1;
            @L1.canceled -= instance.OnL1;
            @L2.started -= instance.OnL2;
            @L2.performed -= instance.OnL2;
            @L2.canceled -= instance.OnL2;
            @L3.started -= instance.OnL3;
            @L3.performed -= instance.OnL3;
            @L3.canceled -= instance.OnL3;
            @L4.started -= instance.OnL4;
            @L4.performed -= instance.OnL4;
            @L4.canceled -= instance.OnL4;
            @Barge.started -= instance.OnBarge;
            @Barge.performed -= instance.OnBarge;
            @Barge.canceled -= instance.OnBarge;
            @AlgaeHigh.started -= instance.OnAlgaeHigh;
            @AlgaeHigh.performed -= instance.OnAlgaeHigh;
            @AlgaeHigh.canceled -= instance.OnAlgaeHigh;
            @AlgaeLow.started -= instance.OnAlgaeLow;
            @AlgaeLow.performed -= instance.OnAlgaeLow;
            @AlgaeLow.canceled -= instance.OnAlgaeLow;
            @AlgaeHold.started -= instance.OnAlgaeHold;
            @AlgaeHold.performed -= instance.OnAlgaeHold;
            @AlgaeHold.canceled -= instance.OnAlgaeHold;
            @Climb.started -= instance.OnClimb;
            @Climb.performed -= instance.OnClimb;
            @Climb.canceled -= instance.OnClimb;
        }

        public void RemoveCallbacks(IRobotActions instance)
        {
            if (m_Wrapper.m_RobotActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRobotActions instance)
        {
            foreach (var item in m_Wrapper.m_RobotActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RobotActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RobotActions @Robot => new RobotActions(this);
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IRobotActions
    {
        void OnDrive(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnIntake(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnHub(InputAction.CallbackContext context);
        void OnPassLeft(InputAction.CallbackContext context);
        void OnPassRight(InputAction.CallbackContext context);
        void OnRobotSpecial(InputAction.CallbackContext context);
        void OnHumanPlayerDump(InputAction.CallbackContext context);
        void OnFlipCamera(InputAction.CallbackContext context);
        void OnRestart(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnAutoAlign(InputAction.CallbackContext context);
        void OnL1(InputAction.CallbackContext context);
        void OnL2(InputAction.CallbackContext context);
        void OnL3(InputAction.CallbackContext context);
        void OnL4(InputAction.CallbackContext context);
        void OnBarge(InputAction.CallbackContext context);
        void OnAlgaeHigh(InputAction.CallbackContext context);
        void OnAlgaeLow(InputAction.CallbackContext context);
        void OnAlgaeHold(InputAction.CallbackContext context);
        void OnClimb(InputAction.CallbackContext context);
    }
}
